### ISSUE TITLE
Support Google Apps Domains

### ISSUE THREAD

**Issue by bellingard** [SonarCommunity/sonar-openid#9]
(coming from http://jira.sonarsource.com/browse/SONAROPNID-16)

Google discovery process is a bit different when using google apps domains instead of standard google accounts.
The property sonar.openid.providerUrl should be set to https://www.google.com/accounts/o8/site-xrds?hd=<domain.com>. It correctly redirects to the login form of the Google App Domain, but then it fails when validating the response :
```
org.openid4java.discovery.yadis.YadisException: 0x706: GET failed on http://sonarsource.com/openid?id=116597769904737558836 : 404
	at org.openid4java.discovery.yadis.YadisResolver.retrieveXrdsLocation(YadisResolver.java:411)
	at org.openid4java.discovery.yadis.YadisResolver.discover(YadisResolver.java:252)
	at org.openid4java.discovery.yadis.YadisResolver.discover(YadisResolver.java:232)
	at org.openid4java.discovery.yadis.YadisResolver.discover(YadisResolver.java:166)
	at org.openid4java.discovery.Discovery.discover(Discovery.java:147)
	at org.openid4java.consumer.ConsumerManager.verifyDiscovered2(ConsumerManager.java:1693)
	at org.openid4java.consumer.ConsumerManager.verifyDiscovered(ConsumerManager.java:1521)
	at org.openid4java.consumer.ConsumerManager.verify(ConsumerManager.java:1160)
	at org.sonar.plugins.openid.OpenIdClient.verify(OpenIdClient.java:140)
	at org.sonar.plugins.openid.OpenIdValidationFilter.doFilter(OpenIdValidationFilter.java:62)
	at org.sonar.server.platform.ServletFilters$GodFilterChain.doFilter(ServletFilters.java:102)
	at org.sonar.server.platform.ServletFilters.doFilter(ServletFilters.java:73)
	at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1157)
	at org.sonar.server.ui.DatabaseSessionFilter.doFilter(DatabaseSessionFilter.java:34)
	at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1157)
	at org.mortbay.servlet.UserAgentFilter.doFilter(UserAgentFilter.java:78)
	at org.mortbay.servlet.GzipFilter.doFilter(GzipFilter.java:131)
	at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1157)
	at org.mortbay.jetty.servlet.ServletHandler.handle(ServletHandler.java:388)
	at org.mortbay.jetty.security.SecurityHandler.handle(SecurityHandler.java:216)
	at org.mortbay.jetty.servlet.SessionHandler.handle(SessionHandler.java:182)
	at org.mortbay.jetty.handler.ContextHandler.handle(ContextHandler.java:765)
	at org.mortbay.jetty.webapp.WebAppContext.handle(WebAppContext.java:440)
	at org.mortbay.jetty.handler.HandlerWrapper.handle(HandlerWrapper.java:152)
	at org.mortbay.jetty.Server.handle(Server.java:326)
	at org.mortbay.jetty.HttpConnection.handleRequest(HttpConnection.java:542)
	at org.mortbay.jetty.HttpConnection$RequestHandler.headerComplete(HttpConnection.java:926)
	at org.mortbay.jetty.HttpParser.parseNext(HttpParser.java:549)
	at org.mortbay.jetty.HttpParser.parseAvailable(HttpParser.java:212)
	at org.mortbay.jetty.HttpConnection.handle(HttpConnection.java:404)
	at org.mortbay.io.nio.SelectChannelEndPoint.run(SelectChannelEndPoint.java:410)
	at org.mortbay.thread.QueuedThreadPool$PoolThread.run(QueuedThreadPool.java:582)
```
Some related links :
- the limitation in openid4java : http://code.google.com/p/openid4java/issues/detail?id=151
- http://stackoverflow.com/a/5572288/229031
- http://stackoverflow.com/questions/1203423/google-apps-domain-as-openid-provider

**Comment by simonbrandhof** [comment]
OpenID is no more supported by Google. As support of Oauth2 is planned in SonarQube, I'm closing this PR.
